### ISSUE TITLE
Can't get this to work

### ISSUE THREAD

**Issue by DarioAhdoot** [reduxkotlin/Reselect#3]
So, the example in the readme isn't valid anymore because `SelectorSubscriberFn` doesn't exist as a symbol. It's not in this repo or in redux-kotlin. I assume that probably changed to `SelectorSubscriberBuilder`, but I can't import that.

`import org.reduxkotlin.SelectorSubscriberBuilder` <-- that fails.

What's the correct way to do this?

**Comment by patjackson52** [comment]
The `SelectorSubscriberFn` in the readme example does not exist by accident. Appears the latest commits are missing.  I plan to look into this next week and update this lib.  For now this is the source of that function...not even sure if this is everything you need, but may help. 
```
/**
 * Helper function that creates a DSL for subscribing to changes in specific state fields and actions to take.
 * Inside the lambda there is access to the current state through the var `state`
 *
 * ex:
 *      val sel = selectorSubscriberFn {
 *          withSingleField({it.foo}, { actionWhenFooChanges() }
 *
 *          withAnyChange {
 *              //called whenever any change happens to state
 *              view.setMessage(state.barMsg) //state is current state
 *          }
 *      }
 */
val selectorSubscriberMap: MutableMap<Any, SelectorSubscriberBuilder<*>> = mutableMapOf()

fun <State : Any, V : Any> selectorSubscriberFn(store: Store<State>, view: V, selectorSubscriberBuilderInit: SelectorSubscriberBuilder<State>.() -> Unit): StoreSubscriber {
    val subscriberBuilder: SelectorSubscriberBuilder<State> = SelectorSubscriberBuilder(store)
    subscriberBuilder.selectorSubscriberBuilderInit()
    selectorSubscriberMap[view] = subscriberBuilder
    return {
        selectorSubscriberMap[view]!!.selectorList.forEach { entry ->
            @Suppress("UNCHECKED_CAST")
            (entry.key as Selector<State, *>).onChangeIn(store.getState()) { entry.value(store.getState()) }
        }
        selectorSubscriberMap[view]!!.withAnyChangeFun?.invoke()
    }
}
```

**Comment by DarioAhdoot** [comment]
@patjackson52 thanks for the help

**Comment by patjackson52** [comment]
@Diarrhio 0.5.5 changes the api a bit.  Still mulling around direction of this lib (whether to be more of a js reselect clone, or a unique library more focused on kotlin & redux)
For the time being the issue reported here should be resolved.  New functions are described in the README.
Pls let me know if any other problems
