### ISSUE TITLE
Failed to resolve 0.4.0

### ISSUE THREAD

**Issue by patricebelisle** [reduxkotlin/Reselect#6]
Trying to use redux-kotlin-reselect:0.4.0 on KMP gives the following error :

ERROR: Failed to resolve: org.reduxkotlin:redux-kotlin-reselect:0.4.0

Looking at the maven repository here : https://mvnrepository.com/artifact/org.reduxkotlin/redux-kotlin-reselect-ios
I see the lastest version seems to be 0.2.10, which could explain why I can't use 0.4.0.

**Comment by patjackson52** [comment]
Thanks for reporting.  Hope to have an update for this next week

**Comment by melbic** [comment]
Any news about the state of the updated version?

**Comment by JWood48** [comment]
can resolve 0.5.5 for kotlin 1.4.0 either...

**Comment by patjackson52** [comment]
@JWood48 I've updated the readme with the correct artifact name. 
```
dependencies {
                implementation "org.reduxkotlin:reselect:0.5.5"
            }
```
Pls let me know if you have any more problems.
